services:
  graphql:
    image: kogayushi/graphql
    ports:
      - "8080:8080"
      - "5000:5000"
    mem_limit: 2G
    cpus: "1.0"
  mvc:
    image: kogayushi/mvc
    ports:
      - "18080:8080"
      - "15000:15000"
    mem_limit: 2G
    cpus: "1.0"
  mix:
    image: kogayushi/mix
    ports:
      - "28080:8080"
      - "25000:25000"
    mem_limit: 2G
    cpus: "1.0"
  prometheus:
    image: prom/prometheus:v2.48.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_started