services:
  graphql:
    image: kogayushi/graphql
    ports:
      - "8080:8080"
    mem_limit: 2G
    cpus: "1.0"
  mvc:
    image: kogayushi/mvc
    ports:
      - "18080:8080"
    mem_limit: 2G
    cpus: "1.0"